# Generated by Django 5.2.8 on 2025-11-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bigbasket',
            fields=[
                ('product_name', models.CharField(max_length=100)),
                ('price', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.CharField(max_length=10)),
                ('dimensions', models.CharField(max_length=20)),
                ('model_year', models.DateField()),
                ('body_material', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
